### ISSUE TITLE
master の CI がずっと落ちてる件

### ISSUE THREAD

**Issue by matsubara0507** [IGGG/IGGG.github.io#59]
master に CircleCI の設定がないせいだと思う

というか、結構乱暴に deploy してるし、いい加減ブランチ戦略とか再考してもいいかもしれんね。

なんならナウでヤングな GitHub Actions に乗り換えてもいいかも（依存サービスを減らせるし）。

**Comment by atpons** [comment]
ナウでヤングな人にやってもらおう（提案）

**Comment by matsubara0507** [comment]
GitHub Actions に移行したので落ちなくなったよ
